default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_corsego_development

test:
  <<: *default
  database: rails_corsego_test

production:
  <<: *default
  database: rails_corsego_production
  username: rails_corsego
  password: <%= ENV["RAILS_CORSEGO_DATABASE_PASSWORD"] %>
